CREATE DATABASE `buy_book_db` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

CREATE TABLE book (
  id INT NOT NULL AUTO_INCREMENT,
  bibliography_id INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (bibliography_id) REFERENCES bibliography(id)
);

CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(25) NOT NULL,
  password VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);