CREATE DATABASE `buy_book_db` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  username VARCHAR(25) NOT NULL,
  email VARCHAR(64) NOT NULL,
  password_hash VARCHAR(128) NOT NULL,
  picture VARCHAR(64) NOT NULL
);

CREATE TABLE books (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  author VARCHAR(50) NOT NULL,
  date DATE NOT NULL
);

CREATE TABLE books_users (
  user_id INT NOT NULL,
  book_id INT NOT NULL,
  PRIMARY Key (user_id, book_id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (book_id) REFERENCES books(id)
);